import { Inter } from "next/font/google";
import "./globals.css";

import MainNav from "@/src/components/MainNav";
import ProgressBarComp from "@/src/components/ProgressBarComp";
import Header from "@/src/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        <div className="flex justify-center items-center">
          <Header />
          {children}
          {/* <MainNav index={200} /> */}
          {/* <ProgressBarComp index={200} /> */}
        </div>
      </body>
    </html>
  );
}
